/*
 * HardenCheck — task database (the checklist content)
 *
 * Pure data, no DOM. Each task knows when it applies to a profile, what
 * priority it has, why it matters, and how to do it (per-platform steps).
 * The app (app.js) filters this list by the operator's reported profile and
 * renders a personalized, checkable, exportable checklist. No findings/PASS-
 * FAIL semantics here: this is a guide, not a scanner. Trilingual EN/ES/DE.
 *
 * Profile shape (p):
 *   os      : 'macos' | 'windows' | 'linux' | 'ios' | 'android'
 *   form    : 'computer' | 'mobile'                (derived from os)
 *   apple   : boolean                              (macos | ios)
 *   risk    : 'standard' | 'elevated' | 'high'
 *   travel  : boolean   — crosses borders / travels to hostile contexts
 *   shared  : boolean   — device is shared with other people
 *   sources : boolean   — device holds sensitive sources or material
 *   managed : 'personal' | 'org'
 */
(function () {
  'use strict';

  // ---- categories (keyed to Luis's Marco de Seguridad vector prefixes) ----
  const CATEGORIES = {
    A: { ico: 'key',       name: { en: 'Accounts & sign-in',        es: 'Cuentas y acceso',          de: 'Konten & Anmeldung' } },
    O: { ico: 'refresh',   name: { en: 'Updates & system',          es: 'Actualizaciones y sistema', de: 'Updates & System' } },
    F: { ico: 'lock',      name: { en: 'Device & physical',         es: 'Dispositivo y físico',      de: 'Gerät & physisch' } },
    M: { ico: 'shield',    name: { en: 'Apps & malware hygiene',    es: 'Apps e higiene anti-malware', de: 'Apps & Malware-Hygiene' } },
    N: { ico: 'broadcast', name: { en: 'Network & connectivity',    es: 'Red y conectividad',        de: 'Netzwerk & Verbindung' } },
    W: { ico: 'globe',     name: { en: 'Browser & web',             es: 'Navegador y web',           de: 'Browser & Web' } },
    E: { ico: 'mail',      name: { en: 'Messaging & email',         es: 'Mensajería y correo',       de: 'Messaging & E-Mail' } },
    C: { ico: 'layers',    name: { en: 'Backups & cloud',           es: 'Respaldos y nube',          de: 'Backups & Cloud' } },
    H: { ico: 'crosshair', name: { en: 'High-risk hardening',       es: 'Endurecimiento alto riesgo', de: 'Härtung für hohes Risiko' } },
  };

  const OS_LABEL = { macos: 'macOS', windows: 'Windows', linux: 'Linux', ios: 'iPhone / iPad', android: 'Android' };

  // Shorthand helpers for `applies`.
  const isComputer = (p) => p.form === 'computer';
  const isMobile = (p) => p.form === 'mobile';

  // ============================ TASKS ============================
  const TASKS = [
    // ----------------------------- A: accounts -----------------------------
    {
      id: 'HC-A-001', cat: 'A', prio: 'high',
      title: { en: 'Use a password manager with unique passwords',
               es: 'Usa un gestor de contraseñas con claves únicas',
               de: 'Nutze einen Passwort-Manager mit einzigartigen Passwörtern' },
      why: { en: 'One leaked password should never open a second account. A manager lets every login be long, random and different.',
             es: 'Una contraseña filtrada nunca debe abrir una segunda cuenta. Un gestor permite que cada acceso sea largo, aleatorio y distinto.',
             de: 'Ein geleaktes Passwort darf nie ein zweites Konto öffnen. Ein Manager macht jeden Login lang, zufällig und einzigartig.' },
      how: { all: { en: 'Install a reputable manager (Bitwarden, 1Password, or KeePassXC). Generate a new random password for your email, social and work accounts first. Protect the vault with a long passphrase and 2FA.',
                    es: 'Instala un gestor confiable (Bitwarden, 1Password o KeePassXC). Genera primero una nueva contraseña aleatoria para tu correo, redes y cuentas de trabajo. Protege la bóveda con una frase larga y 2FA.',
                    de: 'Installiere einen seriösen Manager (Bitwarden, 1Password oder KeePassXC). Erzeuge zuerst neue Zufallspasswörter für E-Mail, Social Media und Arbeitskonten. Sichere den Tresor mit einer langen Passphrase und 2FA.' } },
      refs: [{ label: 'EFF SSD: Passwords', url: 'https://ssd.eff.org/module/creating-strong-passwords' }],
      applies: () => true,
    },
    {
      id: 'HC-A-002', cat: 'A', prio: 'critical',
      title: { en: 'Turn on two-factor authentication (avoid SMS)',
               es: 'Activa la verificación en dos pasos (evita SMS)',
               de: 'Aktiviere Zwei-Faktor-Authentifizierung (kein SMS)' },
      why: { en: 'A password alone is not enough against phishing and leaks. App- or key-based 2FA stops most account takeovers; SMS codes can be intercepted or SIM-swapped.',
             es: 'La contraseña sola no basta contra el phishing y las filtraciones. El 2FA por app o llave detiene la mayoría de los secuestros de cuenta; los SMS pueden interceptarse o sufrir SIM-swap.',
             de: 'Ein Passwort allein reicht gegen Phishing und Leaks nicht. App- oder Schlüssel-2FA stoppt die meisten Kontoübernahmen; SMS-Codes lassen sich abfangen oder per SIM-Swap kapern.' },
      how: { all: { en: 'In the security settings of email, social and banking accounts, enable 2FA using an authenticator app (Aegis, Raivo, 1Password) or a hardware key. Save the backup/recovery codes in your password manager. Remove SMS as a 2FA method where you can.',
                    es: 'En la configuración de seguridad de correo, redes y banca, activa el 2FA con una app autenticadora (Aegis, Raivo, 1Password) o una llave física. Guarda los códigos de respaldo en tu gestor. Quita el SMS como método cuando puedas.',
                    de: 'Aktiviere in den Sicherheitseinstellungen von E-Mail, Social Media und Banking 2FA über eine Authenticator-App (Aegis, Raivo, 1Password) oder einen Hardware-Schlüssel. Sichere die Backup-Codes im Passwort-Manager. Entferne SMS als Methode, wo möglich.' } },
      refs: [{ label: 'EFF SSD: 2FA', url: 'https://ssd.eff.org/module/how-enable-two-factor-authentication' }],
      applies: () => true,
    },
    {
      id: 'HC-A-003', cat: 'A', prio: 'critical',
      title: { en: 'Set a strong screen lock / passcode',
               es: 'Configura un bloqueo de pantalla fuerte',
               de: 'Richte eine starke Bildschirmsperre ein' },
      why: { en: 'The lock is what stands between a seized or stolen device and everything on it. A 4-digit PIN is brute-forced in minutes.',
             es: 'El bloqueo es lo único entre un dispositivo decomisado o robado y todo lo que contiene. Un PIN de 4 dígitos se descifra en minutos.',
             de: 'Die Sperre ist das Einzige zwischen einem beschlagnahmten oder gestohlenen Gerät und allem darauf. Eine 4-stellige PIN ist in Minuten geknackt.' },
      how: {
        ios: { en: 'Settings → Face ID & Passcode → Change Passcode → Passcode Options → Custom Alphanumeric Code (or 6+ digits). Enable "Erase Data" after 10 failed attempts.',
               es: 'Ajustes → Face ID y código → Cambiar código → Opciones → Código alfanumérico personalizado (o 6+ dígitos). Activa "Borrar datos" tras 10 intentos fallidos.',
               de: 'Einstellungen → Face ID & Code → Code ändern → Codeoptionen → Eigener alphanumerischer Code (oder 6+ Ziffern). „Daten löschen" nach 10 Fehlversuchen aktivieren.' },
        android: { en: 'Settings → Security → Screen lock → choose PIN (6+ digits) or password, not pattern. Keep biometrics as a convenience layer, not the only lock.',
                   es: 'Ajustes → Seguridad → Bloqueo de pantalla → elige PIN (6+ dígitos) o contraseña, no patrón. La biometría es una capa de comodidad, no el único bloqueo.',
                   de: 'Einstellungen → Sicherheit → Bildschirmsperre → PIN (6+ Ziffern) oder Passwort wählen, kein Muster. Biometrie als Komfort, nicht als einzige Sperre.' },
        all: { en: 'Use a passphrase or 6+ character login password, never a blank or trivial one. Require it on wake and after sleep.',
               es: 'Usa una frase o contraseña de 6+ caracteres, nunca vacía o trivial. Exígela al despertar y tras suspender.',
               de: 'Nutze eine Passphrase oder ein Login-Passwort mit 6+ Zeichen, nie leer oder trivial. Beim Aufwachen und nach dem Ruhezustand verlangen.' } },
      refs: [],
      applies: () => true,
    },
    {
      id: 'HC-A-004', cat: 'A', prio: 'high',
      title: { en: 'Use a hardware security key for your most critical accounts',
               es: 'Usa una llave de seguridad física en tus cuentas más críticas',
               de: 'Nutze einen Hardware-Sicherheitsschlüssel für die kritischsten Konten' },
      why: { en: 'Hardware keys (FIDO2) are the only 2FA that phishing cannot defeat. For a targeted journalist or defender, they are the difference that holds.',
             es: 'Las llaves físicas (FIDO2) son el único 2FA que el phishing no puede vencer. Para un periodista o defensor en la mira, marcan la diferencia.',
             de: 'Hardware-Schlüssel (FIDO2) sind das einzige 2FA, das Phishing nicht aushebelt. Für gezielt angegriffene Journalist:innen oder Verteidiger:innen macht das den Unterschied.' },
      how: { all: { en: 'Buy two keys (e.g. YubiKey, one as backup). Register both on your primary email, the account that recovers everything else, and your social/work logins. Store the backup key somewhere safe and separate.',
                    es: 'Compra dos llaves (p. ej. YubiKey, una de respaldo). Registra ambas en tu correo principal, en la cuenta que recupera a las demás y en tus accesos de trabajo/redes. Guarda la de respaldo en un lugar seguro y aparte.',
                    de: 'Kaufe zwei Schlüssel (z. B. YubiKey, einen als Backup). Registriere beide bei deiner Haupt-E-Mail, beim Konto, das alles andere wiederherstellt, und bei Arbeits-/Social-Logins. Bewahre den Backup-Schlüssel sicher und getrennt auf.' } },
      refs: [],
      applies: (p) => p.risk !== 'standard',
    },

    // ----------------------------- O: updates -----------------------------
    {
      id: 'HC-O-001', cat: 'O', prio: 'critical',
      title: { en: 'Turn on automatic updates and install what is pending',
               es: 'Activa las actualizaciones automáticas e instala lo pendiente',
               de: 'Automatische Updates aktivieren und Ausstehendes installieren' },
      why: { en: 'Most real-world compromises use a known bug that a patch already fixed. Updating closes the door attackers walk through.',
             es: 'La mayoría de los compromisos reales usan un fallo conocido que un parche ya corrigió. Actualizar cierra la puerta por la que entran.',
             de: 'Die meisten realen Kompromittierungen nutzen einen bekannten Bug, den ein Patch längst behoben hat. Updates schließen die Tür, durch die Angreifer gehen.' },
      how: {
        macos: { en: 'System Settings → General → Software Update → turn on all automatic options, then install any pending update now.',
                 es: 'Ajustes → General → Actualización de software → activa todas las opciones automáticas y luego instala lo pendiente ahora.',
                 de: 'Systemeinstellungen → Allgemein → Softwareupdate → alle automatischen Optionen aktivieren, dann ausstehendes Update sofort installieren.' },
        windows: { en: 'Settings → Windows Update → check for updates and install. Turn on "Get the latest updates as soon as available".',
                   es: 'Configuración → Windows Update → buscar e instalar actualizaciones. Activa "Obtener las últimas actualizaciones en cuanto estén disponibles".',
                   de: 'Einstellungen → Windows Update → nach Updates suchen und installieren. „Neueste Updates erhalten, sobald verfügbar" aktivieren.' },
        linux: { en: 'Apply pending updates (e.g. sudo apt update && sudo apt upgrade) and enable unattended security upgrades for your distro.',
                 es: 'Aplica las actualizaciones pendientes (p. ej. sudo apt update && sudo apt upgrade) y habilita las actualizaciones de seguridad desatendidas de tu distro.',
                 de: 'Ausstehende Updates anwenden (z. B. sudo apt update && sudo apt upgrade) und unbeaufsichtigte Sicherheitsupdates deiner Distro aktivieren.' },
        ios: { en: 'Settings → General → Software Update → Automatic Updates → turn on. Install any pending version now, including Rapid Security Responses.',
               es: 'Ajustes → General → Actualización de software → Actualizaciones automáticas → activar. Instala cualquier versión pendiente, incluidas las Respuestas de seguridad rápidas.',
               de: 'Einstellungen → Allgemein → Softwareupdate → Automatische Updates → aktivieren. Ausstehende Version inkl. Rapid Security Responses jetzt installieren.' },
        android: { en: 'Settings → System → System update, and Play Store → Settings → auto-update apps. Install pending Google Play system updates.',
                   es: 'Ajustes → Sistema → Actualización del sistema, y Play Store → Ajustes → autoactualizar apps. Instala las actualizaciones del sistema de Google Play.',
                   de: 'Einstellungen → System → Systemupdate, und Play Store → Einstellungen → Apps automatisch aktualisieren. Google-Play-Systemupdates installieren.' } },
      refs: [],
      applies: () => true,
    },
    {
      id: 'HC-O-002', cat: 'O', prio: 'high',
      title: { en: 'Stop using an end-of-life operating system',
               es: 'Deja de usar un sistema operativo sin soporte',
               de: 'Kein Betriebssystem ohne Support mehr verwenden' },
      why: { en: 'Once an OS stops getting security updates, every new flaw stays open forever. No amount of care makes an unsupported system safe.',
             es: 'Cuando un SO deja de recibir actualizaciones de seguridad, cada nuevo fallo queda abierto para siempre. Ningún cuidado vuelve seguro un sistema sin soporte.',
             de: 'Sobald ein OS keine Sicherheitsupdates mehr erhält, bleibt jede neue Lücke für immer offen. Kein noch so umsichtiges Verhalten macht ein nicht unterstütztes System sicher.' },
      how: { all: { en: 'Check whether your OS version still receives security updates. If not, upgrade to a supported version. If the hardware is too old to upgrade, treat replacement as the goal and, in the meantime, keep the device off sensitive work and the most exposed networks.',
                    es: 'Verifica si tu versión de SO aún recibe actualizaciones de seguridad. Si no, actualiza a una versión con soporte. Si el hardware es muy viejo, plantea reemplazarlo y, mientras tanto, mantén el equipo fuera del trabajo sensible y de las redes más expuestas.',
                    de: 'Prüfe, ob deine OS-Version noch Sicherheitsupdates erhält. Falls nicht, auf eine unterstützte Version aktualisieren. Ist die Hardware zu alt, setze Ersatz als Ziel und halte das Gerät bis dahin von sensibler Arbeit und den exponiertesten Netzen fern.' } },
      refs: [],
      applies: () => true,
    },

    // ----------------------------- F: device/physical -----------------------------
    {
      id: 'HC-F-001', cat: 'F', prio: 'critical',
      title: { en: 'Turn on full-disk encryption',
               es: 'Activa el cifrado de disco completo',
               de: 'Vollständige Datenträgerverschlüsselung aktivieren' },
      why: { en: 'Without it, anyone who holds your computer can read every file by removing the drive, no password needed.',
             es: 'Sin él, cualquiera que tenga tu computadora puede leer cada archivo sacando el disco, sin contraseña.',
             de: 'Ohne sie kann jede:r, der deinen Computer hat, jede Datei durch Ausbau der Platte lesen, ganz ohne Passwort.' },
      how: {
        macos: { en: 'System Settings → Privacy & Security → FileVault → Turn On. Store the recovery key somewhere safe (your password manager), not iCloud if you can avoid it.',
                 es: 'Ajustes → Privacidad y seguridad → FileVault → Activar. Guarda la clave de recuperación en un lugar seguro (tu gestor), no en iCloud si puedes evitarlo.',
                 de: 'Systemeinstellungen → Datenschutz & Sicherheit → FileVault → Aktivieren. Wiederherstellungsschlüssel sicher speichern (Passwort-Manager), möglichst nicht in iCloud.' },
        windows: { en: 'Use BitLocker (Settings → Privacy & security → Device encryption, or BitLocker on Pro). Save the recovery key to your password manager, not only your Microsoft account.',
                   es: 'Usa BitLocker (Configuración → Privacidad y seguridad → Cifrado de dispositivo, o BitLocker en Pro). Guarda la clave de recuperación en tu gestor, no solo en tu cuenta de Microsoft.',
                   de: 'BitLocker nutzen (Einstellungen → Datenschutz & Sicherheit → Geräteverschlüsselung, oder BitLocker bei Pro). Wiederherstellungsschlüssel im Passwort-Manager sichern, nicht nur im Microsoft-Konto.' },
        linux: { en: 'If you did not enable LUKS full-disk encryption at install, the reliable path is to back up, reinstall with encryption enabled, and restore.',
                 es: 'Si no activaste el cifrado de disco LUKS al instalar, lo fiable es respaldar, reinstalar con cifrado activado y restaurar.',
                 de: 'Falls du LUKS-Vollverschlüsselung bei der Installation nicht aktiviert hast, ist der sichere Weg: sichern, mit Verschlüsselung neu installieren, zurückspielen.' } },
      refs: [],
      applies: isComputer,
    },
    {
      id: 'HC-F-002', cat: 'F', prio: 'high',
      title: { en: 'Confirm your phone is encrypted',
               es: 'Confirma que tu teléfono está cifrado',
               de: 'Bestätige, dass dein Telefon verschlüsselt ist' },
      why: { en: 'Phone storage is only encrypted when a real passcode protects it. With no passcode, the data is readable if the device is taken.',
             es: 'El almacenamiento del teléfono solo se cifra cuando un código real lo protege. Sin código, los datos son legibles si te quitan el equipo.',
             de: 'Der Telefonspeicher ist nur verschlüsselt, wenn ein echter Code ihn schützt. Ohne Code sind die Daten lesbar, wenn das Gerät genommen wird.' },
      how: {
        ios: { en: 'Setting a passcode (task above) enables hardware encryption automatically. Confirm "Data protection is enabled" at the bottom of Settings → Face ID & Passcode.',
               es: 'Poner un código (tarea anterior) activa el cifrado por hardware automáticamente. Confirma "La protección de datos está activada" al final de Ajustes → Face ID y código.',
               de: 'Ein Code (Aufgabe oben) aktiviert die Hardwareverschlüsselung automatisch. Bestätige „Datenschutz ist aktiviert" unten in Einstellungen → Face ID & Code.' },
        android: { en: 'Modern Android encrypts by default once a screen lock is set. Confirm a PIN/password lock is active; on older devices check Settings → Security → Encryption.',
                   es: 'Android moderno cifra por defecto al fijar un bloqueo. Confirma que hay PIN/contraseña; en equipos viejos revisa Ajustes → Seguridad → Cifrado.',
                   de: 'Modernes Android verschlüsselt standardmäßig, sobald eine Sperre gesetzt ist. PIN/Passwort-Sperre bestätigen; bei älteren Geräten Einstellungen → Sicherheit → Verschlüsselung prüfen.' } },
      refs: [],
      applies: isMobile,
    },
    {
      id: 'HC-F-003', cat: 'F', prio: 'high',
      title: { en: 'Enable remote find & wipe',
               es: 'Activa localizar y borrar a distancia',
               de: 'Geräte-Suche & Fernlöschung aktivieren' },
      why: { en: 'If the device is lost or seized, you want the option to locate it and to erase it remotely before anyone gets in.',
             es: 'Si pierdes el equipo o te lo decomisan, quieres poder localizarlo y borrarlo a distancia antes de que alguien entre.',
             de: 'Geht das Gerät verloren oder wird beschlagnahmt, willst du es orten und aus der Ferne löschen können, bevor jemand hineinkommt.' },
      how: {
        macos: { en: 'System Settings → your name → Find My → Find My Mac → On.',
                 es: 'Ajustes → tu nombre → Buscar → Buscar mi Mac → Activar.',
                 de: 'Systemeinstellungen → dein Name → Wo ist? → Meinen Mac suchen → Ein.' },
        windows: { en: 'Settings → Privacy & security → Find my device → On (requires a Microsoft account).',
                   es: 'Configuración → Privacidad y seguridad → Buscar mi dispositivo → Activar (requiere cuenta de Microsoft).',
                   de: 'Einstellungen → Datenschutz & Sicherheit → Mein Gerät suchen → Ein (erfordert Microsoft-Konto).' },
        ios: { en: 'Settings → your name → Find My → Find My iPhone → On, with "Find My network" and "Send Last Location" enabled.',
               es: 'Ajustes → tu nombre → Buscar → Buscar mi iPhone → Activar, con "Red de Buscar" y "Enviar última ubicación".',
               de: 'Einstellungen → dein Name → Wo ist? → Mein iPhone suchen → Ein, mit „Wo-ist-Netzwerk" und „Letzten Standort senden".' },
        android: { en: 'Settings → Security → Find My Device → On, and confirm it works at android.com/find.',
                   es: 'Ajustes → Seguridad → Encontrar mi dispositivo → Activar, y verifica en android.com/find.',
                   de: 'Einstellungen → Sicherheit → Mein Gerät finden → Ein, und auf android.com/find prüfen.' },
        linux: { en: 'No standard built-in. Rely on full-disk encryption plus an external tracker if needed; encryption is what protects the data.',
                 es: 'No hay opción estándar integrada. Apóyate en el cifrado de disco y, si hace falta, un rastreador externo; el cifrado es lo que protege los datos.',
                 de: 'Keine Standardfunktion. Verlasse dich auf Datenträgerverschlüsselung und ggf. externen Tracker; die Verschlüsselung schützt die Daten.' } },
      refs: [],
      applies: () => true,
    },
    {
      id: 'HC-F-004', cat: 'F', prio: 'medium',
      title: { en: 'Set a firmware / BIOS password',
               es: 'Pon una contraseña de firmware / BIOS',
               de: 'Firmware- / BIOS-Passwort setzen' },
      why: { en: 'It blocks someone with physical access from booting another OS, resetting your settings, or bypassing your disk encryption setup.',
             es: 'Impide que alguien con acceso físico arranque otro SO, reinicie tus ajustes o evada la configuración de cifrado del disco.',
             de: 'Es verhindert, dass jemand mit physischem Zugang ein anderes OS startet, Einstellungen zurücksetzt oder die Verschlüsselungs-Konfiguration umgeht.' },
      how: {
        macos: { en: 'On Apple Silicon this is covered by FileVault + your login password and Activation Lock; ensure both are on. On older Intel Macs, set a Firmware Password in Recovery.',
                 es: 'En Apple Silicon esto lo cubren FileVault + tu contraseña de inicio y el Bloqueo de activación; asegúralos. En Mac Intel antiguos, pon una contraseña de firmware en Recuperación.',
                 de: 'Bei Apple Silicon decken FileVault + Login-Passwort und Aktivierungssperre dies ab; beides sicherstellen. Bei älteren Intel-Macs ein Firmware-Passwort im Recovery setzen.' },
        windows: { en: 'Enter UEFI/BIOS setup at boot and set a supervisor/administrator password; keep Secure Boot enabled.',
                   es: 'Entra al UEFI/BIOS al arrancar y pon una contraseña de supervisor/administrador; mantén Secure Boot activado.',
                   de: 'Beim Start ins UEFI/BIOS und ein Supervisor-/Administrator-Passwort setzen; Secure Boot aktiviert lassen.' },
        linux: { en: 'Enter UEFI/BIOS setup and set a supervisor password; keep Secure Boot on where your distro supports it.',
                 es: 'Entra al UEFI/BIOS y pon una contraseña de supervisor; mantén Secure Boot si tu distro lo admite.',
                 de: 'Ins UEFI/BIOS und ein Supervisor-Passwort setzen; Secure Boot aktiviert lassen, wo deine Distro es unterstützt.' } },
      refs: [],
      applies: (p) => isComputer(p) && p.risk !== 'standard',
    },
    {
      id: 'HC-F-005', cat: 'F', prio: 'medium',
      title: { en: 'Lock down the lock screen and ports',
               es: 'Endurece la pantalla de bloqueo y los puertos',
               de: 'Sperrbildschirm und Anschlüsse absichern' },
      why: { en: 'Message previews and accessory ports leak information and create attack paths even while the device is "locked".',
             es: 'Las vistas previas de mensajes y los puertos de accesorios filtran información y abren rutas de ataque aun con el equipo "bloqueado".',
             de: 'Nachrichten-Vorschauen und Zubehör-Anschlüsse verraten Informationen und schaffen Angriffswege, selbst wenn das Gerät „gesperrt" ist.' },
      how: {
        ios: { en: 'Settings → Notifications → Show Previews → When Unlocked. Settings → Face ID & Passcode → turn off lock-screen access to Control Center and USB Accessories ("Accessories" while locked = off).',
               es: 'Ajustes → Notificaciones → Mostrar vistas previas → Con el iPhone desbloqueado. Ajustes → Face ID y código → desactiva el acceso desde el bloqueo a Centro de control y Accesorios USB.',
               de: 'Einstellungen → Mitteilungen → Vorschau zeigen → Wenn entsperrt. Einstellungen → Face ID & Code → Kontrollzentrum und USB-Zubehör im Sperrzustand deaktivieren.' },
        android: { en: 'Settings → Notifications → lock-screen notifications → hide sensitive content. Disable USB data while locked where your device offers it.',
                   es: 'Ajustes → Notificaciones → en pantalla de bloqueo → ocultar contenido sensible. Desactiva datos por USB con el equipo bloqueado si tu dispositivo lo permite.',
                   de: 'Einstellungen → Mitteilungen → Sperrbildschirm → vertrauliche Inhalte ausblenden. USB-Daten im Sperrzustand deaktivieren, wo möglich.' } },
      refs: [],
      applies: (p) => isMobile(p) && (p.risk !== 'standard' || p.sources),
    },

    // ----------------------------- M: apps/malware -----------------------------
    {
      id: 'HC-M-001', cat: 'M', prio: 'high',
      title: { en: 'Install software only from official, trusted sources',
               es: 'Instala software solo de fuentes oficiales y confiables',
               de: 'Software nur aus offiziellen, vertrauenswürdigen Quellen' },
      why: { en: 'Sideloaded apps, cracked software and "free" downloads are the most common way targeted malware reaches a device.',
             es: 'Las apps fuera de tienda, el software pirata y las descargas "gratis" son la vía más común de malware dirigido a un dispositivo.',
             de: 'Sideloading, geknackte Software und „kostenlose" Downloads sind der häufigste Weg, auf dem gezielte Malware ein Gerät erreicht.' },
      how: {
        all: { en: 'Use the official app store or the vendor\'s own site. Avoid third-party "download" portals and pirated software. On desktop, verify the publisher before allowing an install.',
               es: 'Usa la tienda oficial o el sitio del fabricante. Evita portales de "descargas" de terceros y software pirata. En escritorio, verifica al editor antes de permitir la instalación.',
               de: 'Nutze den offiziellen App Store oder die Hersteller-Seite. Meide Drittanbieter-„Download"-Portale und Raubkopien. Am Desktop den Herausgeber vor der Installation prüfen.' },
        android: { en: 'Keep "Install unknown apps" disabled for every app. Prefer Play Store or the official site; avoid random APKs.',
                   es: 'Mantén "Instalar apps desconocidas" desactivado para cada app. Prefiere Play Store o el sitio oficial; evita APKs sueltos.',
                   de: '„Unbekannte Apps installieren" für jede App deaktiviert lassen. Play Store oder offizielle Seite bevorzugen; keine zufälligen APKs.' } },
      refs: [],
      applies: () => true,
    },
    {
      id: 'HC-M-002', cat: 'M', prio: 'medium',
      title: { en: 'Audit installed apps and their permissions',
               es: 'Audita las apps instaladas y sus permisos',
               de: 'Installierte Apps und ihre Berechtigungen prüfen' },
      why: { en: 'Apps you forgot about still hold access to your camera, mic, location and files. Every unused app is attack surface for nothing.',
             es: 'Las apps que olvidaste siguen con acceso a tu cámara, micro, ubicación y archivos. Cada app sin uso es superficie de ataque a cambio de nada.',
             de: 'Vergessene Apps haben weiter Zugriff auf Kamera, Mikro, Standort und Dateien. Jede ungenutzte App ist Angriffsfläche ohne Gegenwert.' },
      how: {
        all: { en: 'List your installed apps; uninstall anything you no longer use. For what remains, revoke camera, microphone, location and contacts access from apps that do not truly need it.',
               es: 'Lista tus apps instaladas; desinstala lo que ya no uses. A lo que quede, quítale acceso a cámara, micrófono, ubicación y contactos cuando no lo necesite de verdad.',
               de: 'Liste installierte Apps; deinstalliere Ungenutztes. Beim Rest Kamera-, Mikrofon-, Standort- und Kontaktzugriff entziehen, wo nicht wirklich nötig.' },
        ios: { en: 'Settings → Privacy & Security to review each permission category and see which apps hold it.',
               es: 'Ajustes → Privacidad y seguridad para revisar cada categoría de permiso y qué apps lo tienen.',
               de: 'Einstellungen → Datenschutz & Sicherheit, um jede Berechtigungskategorie und die Apps darin zu prüfen.' },
        android: { en: 'Settings → Privacy → Permission manager to review by category; use "Remove permissions if app unused".',
                   es: 'Ajustes → Privacidad → Administrador de permisos por categoría; usa "Eliminar permisos si la app no se usa".',
                   de: 'Einstellungen → Datenschutz → Berechtigungsmanager nach Kategorie; „Berechtigungen bei Nichtnutzung entfernen" verwenden.' } },
      refs: [],
      applies: () => true,
    },

    // ----------------------------- N: network -----------------------------
    {
      id: 'HC-N-001', cat: 'N', prio: 'medium',
      title: { en: 'Turn on the firewall',
               es: 'Activa el cortafuegos',
               de: 'Firewall aktivieren' },
      why: { en: 'A firewall stops other machines on a café, hotel or shared network from reaching services on your computer.',
             es: 'Un cortafuegos evita que otras máquinas en la red de un café, hotel o espacio compartido alcancen servicios de tu computadora.',
             de: 'Eine Firewall verhindert, dass andere Rechner in einem Café-, Hotel- oder geteilten Netz Dienste auf deinem Computer erreichen.' },
      how: {
        macos: { en: 'System Settings → Network → Firewall → On. Consider "Block all incoming connections" on hostile networks.',
                 es: 'Ajustes → Red → Firewall → Activar. Considera "Bloquear todas las conexiones entrantes" en redes hostiles.',
                 de: 'Systemeinstellungen → Netzwerk → Firewall → Ein. Auf feindlichen Netzen „Alle eingehenden Verbindungen blockieren" erwägen.' },
        windows: { en: 'Settings → Privacy & security → Windows Security → Firewall & network protection → on for all profiles.',
                   es: 'Configuración → Privacidad y seguridad → Seguridad de Windows → Firewall y protección de red → activo en todos los perfiles.',
                   de: 'Einstellungen → Datenschutz & Sicherheit → Windows-Sicherheit → Firewall- & Netzwerkschutz → für alle Profile aktiv.' },
        linux: { en: 'Enable a firewall (e.g. sudo ufw enable) with a default-deny incoming policy.',
                 es: 'Habilita un cortafuegos (p. ej. sudo ufw enable) con política de denegar entrantes por defecto.',
                 de: 'Firewall aktivieren (z. B. sudo ufw enable) mit Default-Deny für eingehend.' } },
      refs: [],
      applies: isComputer,
    },
    {
      id: 'HC-N-002', cat: 'N', prio: 'high',
      title: { en: 'Protect yourself on untrusted networks',
               es: 'Protégete en redes no confiables',
               de: 'Schütze dich in nicht vertrauenswürdigen Netzen' },
      why: { en: 'On public or border-area Wi-Fi, whoever runs the network can watch or tamper with traffic. A trustworthy VPN closes that window.',
             es: 'En Wi-Fi público o de zona fronteriza, quien controla la red puede ver o manipular el tráfico. Una VPN confiable cierra esa ventana.',
             de: 'In öffentlichem oder Grenz-WLAN kann der Netzbetreiber Datenverkehr mitlesen oder manipulieren. Ein vertrauenswürdiges VPN schließt diese Lücke.' },
      how: { all: { en: 'Use a reputable VPN (Mullvad, IVPN, or your organisation\'s) on any network you do not control. Turn off auto-join for open networks and "forget" ones you will not reuse. Prefer your phone\'s hotspot over open Wi-Fi when it matters.',
                    es: 'Usa una VPN confiable (Mullvad, IVPN o la de tu organización) en cualquier red que no controles. Desactiva la conexión automática a redes abiertas y "olvida" las que no reutilizarás. Prefiere el hotspot de tu teléfono sobre el Wi-Fi abierto cuando importe.',
                    de: 'Nutze ein seriöses VPN (Mullvad, IVPN oder das deiner Organisation) in jedem Netz, das du nicht kontrollierst. Auto-Verbinden mit offenen Netzen deaktivieren und ungenutzte „vergessen". Im Zweifel den Handy-Hotspot statt offenem WLAN nutzen.' } },
      refs: [],
      applies: (p) => p.travel || p.risk !== 'standard',
    },
    {
      id: 'HC-N-003', cat: 'N', prio: 'low',
      title: { en: 'Use encrypted DNS',
               es: 'Usa DNS cifrado',
               de: 'Verschlüsseltes DNS verwenden' },
      why: { en: 'By default the network sees every domain you visit. Encrypted DNS hides that lookup from the local network and its operator.',
             es: 'Por defecto la red ve cada dominio que visitas. El DNS cifrado oculta esa consulta a la red local y a quien la opere.',
             de: 'Standardmäßig sieht das Netz jede Domain, die du besuchst. Verschlüsseltes DNS verbirgt diese Abfrage vor dem lokalen Netz und seinem Betreiber.' },
      how: { all: { en: 'Enable DNS-over-HTTPS in your browser or OS, pointing to a privacy-respecting resolver (e.g. Cloudflare 1.1.1.1, Quad9 9.9.9.9). On iOS/Android you can install the provider\'s configuration profile or Private DNS.',
                    es: 'Activa DNS-over-HTTPS en tu navegador o SO, apuntando a un resolutor que respete la privacidad (p. ej. Cloudflare 1.1.1.1, Quad9 9.9.9.9). En iOS/Android instala el perfil del proveedor o usa DNS privado.',
                    de: 'Aktiviere DNS-over-HTTPS im Browser oder OS mit einem datenschutzfreundlichen Resolver (z. B. Cloudflare 1.1.1.1, Quad9 9.9.9.9). Auf iOS/Android das Anbieter-Profil oder Privates DNS nutzen.' } },
      refs: [],
      applies: () => true,
    },

    // ----------------------------- W: browser/web -----------------------------
    {
      id: 'HC-W-001', cat: 'W', prio: 'medium',
      title: { en: 'Harden your browser',
               es: 'Endurece tu navegador',
               de: 'Härte deinen Browser' },
      why: { en: 'The browser is where most attacks land. A current, tightened browser blocks trackers, downgrade attacks and a lot of drive-by risk.',
             es: 'El navegador es donde aterrizan la mayoría de los ataques. Uno actualizado y ajustado bloquea rastreadores, ataques de degradación y mucho riesgo de descarga.',
             de: 'Im Browser landen die meisten Angriffe. Ein aktueller, gehärteter Browser blockiert Tracker, Downgrade-Angriffe und viel Drive-by-Risiko.' },
      how: { all: { en: 'Keep the browser updated. Turn on HTTPS-Only mode, block third-party cookies, and enable the strict/enhanced tracking protection. Use a content blocker (uBlock Origin). For sensitive browsing, use a separate profile or Tor Browser.',
                    es: 'Mantén el navegador actualizado. Activa el modo solo-HTTPS, bloquea cookies de terceros y la protección reforzada contra rastreo. Usa un bloqueador (uBlock Origin). Para navegación sensible, usa un perfil aparte o Tor Browser.',
                    de: 'Browser aktuell halten. Nur-HTTPS-Modus aktivieren, Drittanbieter-Cookies blockieren und den strengen Tracking-Schutz einschalten. Content-Blocker (uBlock Origin) nutzen. Für sensibles Surfen ein eigenes Profil oder Tor Browser.' } },
      refs: [],
      applies: () => true,
    },
    {
      id: 'HC-W-002', cat: 'W', prio: 'medium',
      title: { en: 'Audit your browser extensions',
               es: 'Audita las extensiones del navegador',
               de: 'Browser-Erweiterungen prüfen' },
      why: { en: 'An extension can read everything you do in the browser. Abandoned or sold-on extensions are a known vector for silent data theft.',
             es: 'Una extensión puede leer todo lo que haces en el navegador. Las extensiones abandonadas o vendidas son un vector conocido de robo silencioso de datos.',
             de: 'Eine Erweiterung kann alles im Browser mitlesen. Verwaiste oder weiterverkaufte Erweiterungen sind ein bekannter Vektor für stillen Datendiebstahl.' },
      how: { all: { en: 'Open your extensions list and remove everything you do not actively use and trust. For the rest, check they are still maintained and limit their site access where the browser allows.',
                    es: 'Abre la lista de extensiones y elimina todo lo que no uses y no confíes activamente. A lo demás, verifica que siga manteniéndose y limita su acceso a sitios cuando el navegador lo permita.',
                    de: 'Erweiterungsliste öffnen und alles entfernen, das du nicht aktiv nutzt und dem du nicht vertraust. Beim Rest prüfen, ob noch gepflegt, und Seitenzugriff einschränken, wo möglich.' } },
      refs: [],
      applies: isComputer,
    },

    // ----------------------------- E: messaging/email -----------------------------
    {
      id: 'HC-E-001', cat: 'E', prio: 'high',
      title: { en: 'Move sensitive conversations to end-to-end encrypted messaging',
               es: 'Lleva las conversaciones sensibles a mensajería cifrada de extremo a extremo',
               de: 'Sensible Gespräche in Ende-zu-Ende-verschlüsseltes Messaging verlegen' },
      why: { en: 'SMS and ordinary email can be read in transit and at rest. Signal keeps content readable only to you and the person you wrote to.',
             es: 'El SMS y el correo común pueden leerse en tránsito y en reposo. Signal mantiene el contenido legible solo para ti y la persona a quien escribes.',
             de: 'SMS und gewöhnliche E-Mail sind unterwegs und im Speicher lesbar. Signal hält Inhalte nur für dich und deine:n Gesprächspartner:in lesbar.' },
      how: { all: { en: 'Use Signal for sensitive chats and calls. Turn on disappearing messages, set a registration lock PIN, and verify safety numbers with key contacts. Keep your own copies of anything you must retain, outside the chat.',
                    es: 'Usa Signal para chats y llamadas sensibles. Activa los mensajes que desaparecen, pon un PIN de bloqueo de registro y verifica los números de seguridad con tus contactos clave. Guarda copias propias de lo que debas conservar, fuera del chat.',
                    de: 'Nutze Signal für sensible Chats und Anrufe. Verschwindende Nachrichten aktivieren, eine Registrierungssperre-PIN setzen und Sicherheitsnummern mit Schlüsselkontakten verifizieren. Aufzubewahrendes selbst außerhalb des Chats sichern.' } },
      refs: [{ label: 'Signal', url: 'https://signal.org/' }],
      applies: () => true,
    },
    {
      id: 'HC-E-002', cat: 'E', prio: 'high',
      title: { en: 'Build a phishing reflex',
               es: 'Desarrolla un reflejo anti-phishing',
               de: 'Einen Phishing-Reflex aufbauen' },
      why: { en: 'Targeted phishing, not exotic exploits, is how most journalists and defenders actually get compromised. A moment of doubt is the defence.',
             es: 'El phishing dirigido, no los exploits exóticos, es como de verdad se compromete a la mayoría de periodistas y defensores. Un instante de duda es la defensa.',
             de: 'Gezieltes Phishing, nicht exotische Exploits, ist der Weg, auf dem die meisten Journalist:innen und Verteidiger:innen tatsächlich kompromittiert werden. Ein Moment des Zweifels ist die Verteidigung.' },
      how: { all: { en: 'Treat unexpected login links, urgent requests and attachments as suspect, even from known contacts. Verify through a second channel before clicking or replying. Never type a password into a page you reached from a link; navigate to the site yourself. Hardware keys (task above) make this much safer.',
                    es: 'Trata como sospechosos los enlaces de inicio de sesión inesperados, las peticiones urgentes y los adjuntos, incluso de contactos conocidos. Verifica por un segundo canal antes de hacer clic o responder. Nunca escribas una contraseña en una página a la que llegaste por un enlace; entra tú al sitio. Las llaves físicas (tarea anterior) lo hacen mucho más seguro.',
                    de: 'Behandle unerwartete Login-Links, dringende Bitten und Anhänge als verdächtig, auch von bekannten Kontakten. Über einen zweiten Kanal verifizieren, bevor du klickst oder antwortest. Nie ein Passwort auf einer Seite eingeben, die du über einen Link erreicht hast; die Seite selbst aufrufen. Hardware-Schlüssel (Aufgabe oben) machen das viel sicherer.' } },
      refs: [{ label: 'EFF SSD: Phishing', url: 'https://ssd.eff.org/module/how-avoid-phishing-attacks' }],
      applies: () => true,
    },

    // ----------------------------- C: backups/cloud -----------------------------
    {
      id: 'HC-C-001', cat: 'C', prio: 'high',
      title: { en: 'Keep encrypted, tested backups',
               es: 'Mantén respaldos cifrados y probados',
               de: 'Verschlüsselte, getestete Backups führen' },
      why: { en: 'Ransomware, seizure, theft and simple failure all end the same way without a backup. Encrypted backups protect the data even if the copy is taken.',
             es: 'El ransomware, el decomiso, el robo y un simple fallo terminan igual sin respaldo. Los respaldos cifrados protegen los datos aun si se llevan la copia.',
             de: 'Ransomware, Beschlagnahme, Diebstahl und schlichtes Versagen enden ohne Backup gleich. Verschlüsselte Backups schützen die Daten, selbst wenn die Kopie genommen wird.' },
      how: { all: { en: 'Follow 3-2-1: three copies, two media, one off-site. Encrypt the backup (Time Machine with encryption, an encrypted external drive, or an end-to-end encrypted cloud). Once in a while, actually restore a file to confirm it works.',
                    es: 'Sigue 3-2-1: tres copias, dos medios, una fuera del sitio. Cifra el respaldo (Time Machine cifrado, un disco externo cifrado o una nube de extremo a extremo). De vez en cuando, restaura un archivo para confirmar que sirve.',
                    de: 'Befolge 3-2-1: drei Kopien, zwei Medien, eine extern. Backup verschlüsseln (Time Machine mit Verschlüsselung, verschlüsselte externe Platte oder Ende-zu-Ende-Cloud). Ab und zu eine Datei testweise wiederherstellen.' } },
      refs: [],
      applies: () => true,
    },
    {
      id: 'HC-C-002', cat: 'C', prio: 'high',
      title: { en: 'Secure your account recovery',
               es: 'Asegura la recuperación de tus cuentas',
               de: 'Konto-Wiederherstellung absichern' },
      why: { en: 'Attackers often skip your password and go straight for "forgot password". Weak recovery (a SMS number, an old email) is the real back door.',
             es: 'Los atacantes suelen saltarse la contraseña e ir directo a "olvidé mi contraseña". Una recuperación débil (un número SMS, un correo viejo) es la verdadera puerta trasera.',
             de: 'Angreifer überspringen oft das Passwort und gehen direkt auf „Passwort vergessen". Schwache Wiederherstellung (SMS-Nummer, alte E-Mail) ist die eigentliche Hintertür.' },
      how: { all: { en: 'On your primary email and key accounts, review recovery methods: remove stale phone numbers and old addresses, store one-time recovery codes in your password manager, and prefer app/key-based recovery over SMS.',
                    es: 'En tu correo principal y cuentas clave, revisa los métodos de recuperación: quita números viejos y direcciones antiguas, guarda los códigos de un solo uso en tu gestor y prefiere la recuperación por app/llave sobre el SMS.',
                    de: 'Bei Haupt-E-Mail und Schlüsselkonten Wiederherstellungsmethoden prüfen: alte Nummern und Adressen entfernen, Einmal-Codes im Passwort-Manager sichern, App-/Schlüssel-Wiederherstellung statt SMS bevorzugen.' } },
      refs: [],
      applies: () => true,
    },
    {
      id: 'HC-C-003', cat: 'C', prio: 'medium',
      title: { en: 'Review third-party access to your accounts',
               es: 'Revisa el acceso de terceros a tus cuentas',
               de: 'Drittanbieter-Zugriff auf deine Konten prüfen' },
      why: { en: 'Old "Sign in with…" grants and connected apps can keep reading your mail, files or contacts long after you stopped using them.',
             es: 'Los antiguos "Iniciar sesión con…" y apps conectadas pueden seguir leyendo tu correo, archivos o contactos mucho después de que dejaste de usarlos.',
             de: 'Alte „Anmelden mit…"-Freigaben und verbundene Apps können deine Mail, Dateien oder Kontakte noch lange weiterlesen, nachdem du sie nicht mehr nutzt.' },
      how: { all: { en: 'In the security settings of Google, Apple, Microsoft and your social accounts, open "connected apps" / "third-party access" and revoke anything unfamiliar or unused.',
                    es: 'En la configuración de seguridad de Google, Apple, Microsoft y tus redes, abre "apps conectadas" / "acceso de terceros" y revoca lo desconocido o sin uso.',
                    de: 'In den Sicherheitseinstellungen von Google, Apple, Microsoft und Social-Konten „verbundene Apps" / „Drittanbieter-Zugriff" öffnen und Unbekanntes oder Ungenutztes widerrufen.' } },
      refs: [],
      applies: () => true,
    },

    // ----------------------------- H: high-risk -----------------------------
    {
      id: 'HC-H-001', cat: 'H', prio: 'critical',
      title: { en: 'Turn on Lockdown Mode',
               es: 'Activa el modo de aislamiento (Lockdown)',
               de: 'Aktiviere den Sperrmodus (Lockdown)' },
      why: { en: 'Apple\'s Lockdown Mode strips out the exact features mercenary spyware abuses. For a likely target, the trade-off in convenience is worth it.',
             es: 'El modo Lockdown de Apple elimina justo las funciones que abusa el spyware mercenario. Para un blanco probable, la incomodidad vale la pena.',
             de: 'Apples Sperrmodus entfernt genau die Funktionen, die Söldner-Spyware missbraucht. Für ein wahrscheinliches Ziel ist der Komfortverzicht es wert.' },
      how: {
        ios: { en: 'Settings → Privacy & Security → Lockdown Mode → Turn On Lockdown Mode, then restart.',
               es: 'Ajustes → Privacidad y seguridad → Modo Lockdown → Activar, luego reinicia.',
               de: 'Einstellungen → Datenschutz & Sicherheit → Sperrmodus → Aktivieren, dann neu starten.' },
        macos: { en: 'System Settings → Privacy & Security → Lockdown Mode → Turn On, then restart.',
                 es: 'Ajustes → Privacidad y seguridad → Modo Lockdown → Activar, luego reinicia.',
                 de: 'Systemeinstellungen → Datenschutz & Sicherheit → Sperrmodus → Aktivieren, dann neu starten.' } },
      refs: [{ label: 'Apple: Lockdown Mode', url: 'https://support.apple.com/en-us/105120' }],
      applies: (p) => p.apple && p.risk === 'high',
    },
    {
      id: 'HC-H-002', cat: 'H', prio: 'high',
      title: { en: 'Compartmentalize sensitive work',
               es: 'Compartimenta el trabajo sensible',
               de: 'Sensible Arbeit kompartimentieren' },
      why: { en: 'If one device or account is compromised, separation keeps your most sensitive material out of reach. Mixing everything makes one breach total.',
             es: 'Si un dispositivo o cuenta cae, la separación deja tu material más sensible fuera de alcance. Mezclar todo convierte una sola brecha en total.',
             de: 'Fällt ein Gerät oder Konto, hält Trennung dein sensibelstes Material außer Reichweite. Alles zu vermischen macht aus einem Einbruch einen totalen.' },
      how: { all: { en: 'Keep separate accounts (and, where possible, a separate device or user profile) for your most sensitive sources and material. Do not log your high-risk work into your everyday phone\'s main account. Decide deliberately what lives where.',
                    es: 'Mantén cuentas separadas (y, si puedes, un dispositivo o perfil de usuario aparte) para tus fuentes y material más sensibles. No mezcles tu trabajo de alto riesgo con la cuenta principal de tu teléfono diario. Decide a conciencia qué vive dónde.',
                    de: 'Halte separate Konten (und wo möglich ein eigenes Gerät oder Benutzerprofil) für deine sensibelsten Quellen und Materialien. Hochrisiko-Arbeit nicht im Hauptkonto deines Alltagshandys ablegen. Bewusst entscheiden, was wo lebt.' } },
      refs: [],
      applies: (p) => p.risk === 'high' || p.sources,
    },
    {
      id: 'HC-H-003', cat: 'H', prio: 'high',
      title: { en: 'Set up a spyware triage routine',
               es: 'Establece una rutina de triaje de spyware',
               de: 'Eine Spyware-Triage-Routine einrichten' },
      why: { en: 'Targeted mobile spyware is silent by design. Periodic, evidence-based checks are the only way to catch it rather than assume you are clean.',
             es: 'El spyware móvil dirigido es silencioso por diseño. Las revisiones periódicas basadas en evidencia son la única forma de detectarlo en vez de suponerte limpio.',
             de: 'Gezielte mobile Spyware ist bewusst lautlos. Regelmäßige, evidenzbasierte Prüfungen sind der einzige Weg, sie zu finden, statt sich für sauber zu halten.' },
      how: { all: { en: 'On a schedule, take an encrypted backup and run Amnesty\'s MVT (Mobile Verification Toolkit) against it, or use the desktop companion (mobile-check) to do the same with a managed toolchain. Keep the analysis on an encrypted drive, not the phone.',
                    es: 'De forma periódica, haz un respaldo cifrado y córrele MVT (Mobile Verification Toolkit de Amnesty), o usa el complemento de escritorio (mobile-check) para hacer lo mismo con una cadena de herramientas gestionada. Guarda el análisis en un disco cifrado, no en el teléfono.',
                    de: 'Regelmäßig ein verschlüsseltes Backup erstellen und mit Amnestys MVT (Mobile Verification Toolkit) prüfen, oder den Desktop-Begleiter (mobile-check) mit verwalteter Toolchain nutzen. Analyse auf verschlüsseltem Datenträger ablegen, nicht auf dem Telefon.' } },
      refs: [{ label: 'Amnesty MVT', url: 'https://github.com/mvt-project/mvt' }],
      applies: (p) => isMobile(p) && p.risk === 'high',
    },
    {
      id: 'HC-H-004', cat: 'H', prio: 'high',
      title: { en: 'Have a travel & border-crossing plan',
               es: 'Ten un plan de viaje y cruce de fronteras',
               de: 'Einen Reise- & Grenzübertritts-Plan haben' },
      why: { en: 'Borders are where devices get inspected, copied or held. The safest data at a crossing is the data that is not on the device.',
             es: 'Las fronteras son donde inspeccionan, copian o retienen dispositivos. El dato más seguro en un cruce es el que no está en el equipo.',
             de: 'Grenzen sind der Ort, an dem Geräte inspiziert, kopiert oder einbehalten werden. Die sichersten Daten am Übergang sind die, die nicht auf dem Gerät liegen.' },
      how: { all: { en: 'Before travelling, minimise what the device carries: move sensitive material to encrypted storage you do not bring, or to an account you log out of. Power the device fully off before a crossing (encryption is strongest at rest). Know your rights, and have a plan if a device is taken: which passwords to rotate, who to tell.',
                    es: 'Antes de viajar, minimiza lo que lleva el equipo: mueve el material sensible a un almacenamiento cifrado que no llevas, o a una cuenta de la que cierras sesión. Apaga el dispositivo por completo antes del cruce (el cifrado es más fuerte en reposo). Conoce tus derechos y ten un plan si te quitan un equipo: qué contraseñas rotar, a quién avisar.',
                    de: 'Vor der Reise minimieren, was das Gerät trägt: sensibles Material auf verschlüsselten Speicher verlagern, den du nicht mitnimmst, oder in ein Konto, von dem du dich abmeldest. Gerät vor dem Übergang vollständig ausschalten (Verschlüsselung ist im Ruhezustand am stärksten). Kenne deine Rechte und habe einen Plan, falls ein Gerät genommen wird: welche Passwörter rotieren, wen informieren.' } },
      refs: [{ label: 'EFF: Border searches', url: 'https://www.eff.org/issues/border-searches' }],
      applies: (p) => p.travel,
    },
    {
      id: 'HC-H-005', cat: 'H', prio: 'medium',
      title: { en: 'Write down an incident plan',
               es: 'Escribe un plan de incidentes',
               de: 'Einen Notfallplan aufschreiben' },
      why: { en: 'In the moment of a compromise or seizure, you will not improvise well. A short plan written calmly now saves hours and mistakes later.',
             es: 'En el momento de un compromiso o decomiso, no improvisarás bien. Un plan corto escrito con calma hoy ahorra horas y errores después.',
             de: 'Im Moment einer Kompromittierung oder Beschlagnahme improvisierst du schlecht. Ein kurzer, jetzt in Ruhe geschriebener Plan spart später Stunden und Fehler.' },
      how: { all: { en: 'Write a one-page plan: who to contact (your org\'s security lead, a digital-rights helpline), which accounts to lock first, where your recovery codes are, and how to wipe remotely. Keep a copy off the device. Rapid Response and Access Now\'s Digital Security Helpline can help.',
                    es: 'Escribe un plan de una página: a quién contactar (el responsable de seguridad de tu organización, una línea de ayuda de derechos digitales), qué cuentas bloquear primero, dónde están tus códigos de recuperación y cómo borrar a distancia. Guarda una copia fuera del equipo. La Línea de Ayuda en Seguridad Digital de Access Now puede ayudar.',
                    de: 'Schreibe einen einseitigen Plan: wen kontaktieren (Sicherheitsverantwortliche deiner Organisation, eine Digital-Rights-Helpline), welche Konten zuerst sperren, wo deine Wiederherstellungscodes liegen und wie aus der Ferne löschen. Eine Kopie außerhalb des Geräts aufbewahren. Access Nows Digital Security Helpline kann helfen.' } },
      refs: [{ label: 'Access Now Helpline', url: 'https://www.accessnow.org/help/' }],
      applies: (p) => p.risk !== 'standard',
    },
  ];

  window.HC_TASKS = TASKS;
  window.HC_CATEGORIES = CATEGORIES;
  window.HC_OS_LABEL = OS_LABEL;
})();
